"""empty message

Revision ID: 66355efc6740
Revises: 7712b31a8fcb
Create Date: 2019-03-13 15:52:25.220834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66355efc6740'
down_revision = '7712b31a8fcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('about_me', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profile', 'about_me')
    # ### end Alembic commands ###
