"""empty message

Revision ID: 7712b31a8fcb
Revises: 
Create Date: 2019-03-13 15:22:07.285341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7712b31a8fcb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interest',
    sa.Column('interest_id', sa.Integer(), nullable=False),
    sa.Column('interest_name', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('interest_id'),
    sa.UniqueConstraint('interest_name')
    )
    op.create_table('profile',
    sa.Column('uin', sa.Integer(), nullable=False),
    sa.Column('email_address', sa.String(length=120), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('first_name', sa.String(length=120), nullable=True),
    sa.Column('last_name', sa.String(length=120), nullable=True),
    sa.Column('user_persona_type', sa.String(length=60), nullable=True),
    sa.Column('primary_contact', sa.String(length=60), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uin'),
    sa.UniqueConstraint('email_address')
    )
    op.create_table('skill',
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('skill_name', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('skill_id'),
    sa.UniqueConstraint('skill_name')
    )
    op.create_table('profile_interest',
    sa.Column('interest_id', sa.Integer(), nullable=False),
    sa.Column('uin', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['interest_id'], ['interest.interest_id'], ),
    sa.ForeignKeyConstraint(['uin'], ['profile.uin'], ),
    sa.PrimaryKeyConstraint('interest_id', 'uin')
    )
    op.create_table('profile_skill',
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('uin', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skill.skill_id'], ),
    sa.ForeignKeyConstraint(['uin'], ['profile.uin'], ),
    sa.PrimaryKeyConstraint('skill_id', 'uin')
    )
    op.create_table('project',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('original_poster', sa.Integer(), nullable=True),
    sa.Column('project_name', sa.String(length=120), nullable=True),
    sa.Column('project_type', sa.String(length=120), nullable=True),
    sa.Column('project_description', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['original_poster'], ['profile.uin'], ),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_index(op.f('ix_project_original_poster'), 'project', ['original_poster'], unique=False)
    op.create_table('participation',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=60), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['profile.uin'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.project_id'], ),
    sa.PrimaryKeyConstraint('project_id', 'member_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('participation')
    op.drop_index(op.f('ix_project_original_poster'), table_name='project')
    op.drop_table('project')
    op.drop_table('profile_skill')
    op.drop_table('profile_interest')
    op.drop_table('skill')
    op.drop_table('profile')
    op.drop_table('interest')
    # ### end Alembic commands ###
